[2023-01-17T14:21:33.075+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.insert_excel_data_to_db manual__2023-01-17T14:19:27.529064+00:00 [queued]>
[2023-01-17T14:21:33.091+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.insert_excel_data_to_db manual__2023-01-17T14:19:27.529064+00:00 [queued]>
[2023-01-17T14:21:33.092+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T14:21:33.093+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 7
[2023-01-17T14:21:33.095+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T14:21:33.110+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): insert_excel_data_to_db> on 2023-01-17 14:19:27.529064+00:00
[2023-01-17T14:21:33.117+0000] {standard_task_runner.py:55} INFO - Started process 5261 to run task
[2023-01-17T14:21:33.123+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'insert_excel_data_to_db', 'manual__2023-01-17T14:19:27.529064+00:00', '--job-id', '1650', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmp82612nds']
[2023-01-17T14:21:33.127+0000] {standard_task_runner.py:83} INFO - Job 1650: Subtask insert_excel_data_to_db
[2023-01-17T14:21:33.202+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.insert_excel_data_to_db manual__2023-01-17T14:19:27.529064+00:00 [running]> on host 76023b3f850c
[2023-01-17T14:21:33.273+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=insert_excel_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T14:19:27.529064+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T14:19:27.529064+00:00
[2023-01-17T14:21:33.288+0000] {logging_mixin.py:137} INFO - Did not connect
[2023-01-17T14:21:33.289+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T14:21:33.301+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v01, task_id=insert_excel_data_to_db, execution_date=20230117T141927, start_date=20230117T142133, end_date=20230117T142133
[2023-01-17T14:21:33.336+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T14:21:33.357+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
